apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: worldpay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worldpay-frontend
  template:
    metadata:
      labels:
        app: worldpay-frontend
    spec:
      containers:
        - name: cont-frontend
          image: <AWS_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
