apiVersion: v1
kind: Secret
metadata:
  name: worldpay-secret
  namespace: worldpay
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://<RDS_ENDPOINT>:5432/worldpay"
  DB_USER: "dbuser"
  DB_PASS: "dbpass"
